# -*- coding: utf-8 -*-
"""HW4_Bio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hO9AEor6lsgXtr6BPYM0ZYc_APrKt3Os
"""

# import numpy as np
from math import log2

sequences = []
sequences_number = int(input())
for i in range(sequences_number):
  temp = input()
  sequences.append(temp)
queri = input()
each_seq_len = len(sequences[0])

char_set = set({})
profile = {}
all_seq = []
for row in range(sequences_number):
  for column in range(each_seq_len):
    char_set.add(sequences[row][column])
char_set = list(char_set)
B = len(char_set)
pseudocount = 2
Denum = sequences_number + B*pseudocount
for char in char_set:
  profile[char] = [2/Denum for _ in range(each_seq_len)]
for column in range(each_seq_len):
  for row in range(sequences_number):
    profile[sequences[row][column]][column] += 1/Denum
for char in char_set:
  temp = sum(profile[char])
  for column in range(each_seq_len):
    profile[char][column] = log2(profile[char][column]/(temp/each_seq_len))

def Make_Seq(all_seq, current_seq, final_seq_length):
  if(len(current_seq) == final_seq_length):
    all_seq.append(current_seq)
  else:
    for i in range(len(current_seq)+1):
      Make_Seq(all_seq, current_seq[:i] + "-" + current_seq[i:], final_seq_length)
if ("-" in profile) :
  for i in range(int(each_seq_len//2)+1,each_seq_len): # need change
    for j in range(len(queri)-i+1):
      Make_Seq(all_seq, queri[j:j+i], each_seq_len)
all_seq = sorted(set(all_seq))

def Score(queri, table):
  score = 0
  location = 0
  for char in queri:
    score += table[char][location]
    location += 1
  return score
all_scores = [Score(item,profile) for item in all_seq]
# print(all_seq[np.argmax(all_scores)])
print(all_seq[all_scores.index(max(all_scores))])